# Generated by Django 3.0.5 on 2020-05-06 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fernet_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', fernet_fields.fields.EncryptedCharField(max_length=100)),
                ('email', fernet_fields.fields.EncryptedEmailField(max_length=100)),
                ('message', fernet_fields.fields.EncryptedCharField(blank=True, max_length=500)),
                ('eeg', models.FileField(blank=True, upload_to='eeg_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
