# Generated by Django 3.0.5 on 2020-05-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='eeg',
            field=models.FileField(blank=True, upload_to='eeg_datasets/'),
        ),
    ]
