# Generated by Django 3.0.5 on 2020-05-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_auto_20200526_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='eeg',
        ),
        migrations.AddField(
            model_name='lead',
            name='eeg_data',
            field=models.FileField(blank=True, upload_to='eeg_data_files/'),
        ),
    ]
