# Generated by Django 3.0.5 on 2020-05-26 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_auto_20200526_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='eeg_data',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
