# Generated by Django 3.0.5 on 2020-05-27 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_auto_20200526_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='eeg_data',
        ),
        migrations.AddField(
            model_name='lead',
            name='eeg',
            field=models.FileField(blank=True, upload_to='eeg_files/'),
        ),
    ]
